name: testing

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-server-build"
  unit-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install deno
    - name: Install Deno and execute unit testing
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export PATH=$PATH:/home/runner/.deno/bin   
        deno --version
        deno info
        deno test -A --unstable
